version: "3.9"

services:
  mysql:
    image: mysql:8.0.33
    container_name: dorm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Yassmine@123456789"
      MYSQL_DATABASE: dormmanager_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dorm-net

  backend:
    build: .
    container_name: dorm_backend
    restart: on-failure
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dormmanager_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Yassmine@123456789"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - dorm-net

  frontend:
    build: ./front
    container_name: dorm_frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - dorm-net

networks:
  dorm-net:

volumes:
  mysql_data:
